name: Front Deployment
on:
  push:
    branches:
      - prod

jobs:
  build:
    name: react build & deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Github Action
        uses: actions/checkout@v3

      - name: Check Node v
        run: node -v

      - name: Install npm Dependencies
        run: npm install

      - name: Build React
        env:
          VITE_BASE_URL: ${{ secrets.VITE_BASE_URL }}
          VITE_LOGIN_URL: ${{ secrets.VITE_LOGIN_URL }}
          VITE_DOMAIN: ${{ secrets.VITE_DOMAIN }}
        run: npm run build

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Upload to S3
        env:
          BUCKET_NAME: ${{ secrets.AWS_S3_BUCKET_NAME }}
        run: |
          aws s3 sync ./dist s3://${{ secrets.AWS_S3_BUCKET_NAME }} --delete
